export const methodTypes = [
  "iframe_ready",
  "iframe_will_reload",
  "web_app_biometry_get_info",
  "web_app_biometry_open_settings",
  "web_app_biometry_request_access",
  "web_app_biometry_request_auth",
  "web_app_biometry_update_token",
  "web_app_close",
  "web_app_close_scan_qr_popup",
  "web_app_data_send",
  "web_app_expand",
  "web_app_invoke_custom_method",
  "web_app_open_invoice",
  "web_app_open_link",
  "web_app_open_popup",
  "web_app_open_scan_qr_popup",
  "web_app_open_tg_link",
  "web_app_read_text_from_clipboard",
  "web_app_ready",
  "web_app_request_phone",
  "web_app_request_theme",
  "web_app_request_viewport",
  "web_app_request_write_access",
  "web_app_set_background_color",
  "web_app_set_header_color",
  "web_app_setup_back_button",
  "web_app_setup_closing_behavior",
  "web_app_setup_main_button",
  "web_app_setup_settings_button",
  "web_app_setup_swipe_behavior",
  "web_app_switch_inline_query",
  "web_app_trigger_haptic_feedback",
] as const;

export type MethodType = (typeof methodTypes)[number];

export const eventTypes = [
  "back_button_pressed",
  "biometry_auth_requested",
  "biometry_info_received",
  "biometry_token_updated",
  "clipboard_text_received",
  "custom_method_invoked",
  "invoice_closed",
  "main_button_pressed",
  "phone_requested",
  "popup_closed",
  "reload_iframe",
  "qr_text_received",
  "scan_qr_popup_closed",
  "set_custom_style",
  "settings_button_pressed",
  "theme_changed",
  "viewport_changed",
  "write_access_requested",
] as const;

export type EventType = (typeof eventTypes)[number];
